import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Remind.me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          id="app"
          className="w-full h-full bg-default flex items-center justify-center"
        >
          <div className="w-app-lg h-[calc(70%-2rem)] flex flex-col gap-2">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
